server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project_manager_dev
    username: postgres
    password: "@kshitiz26"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
